package-lock.json
package.json
src/middlewares/encoding.ts
test/middlewares/cookie.ts
test/middlewares/csrf-header.ts
test/middlewares/encoding.ts
test/middlewares/user-agent.ts
tsconfig.json
typings/form-urlencoded.d.ts

unit tests

---

package-lock.json
package.json
src/executor.ts
src/job.ts
src/main.ts
test/executor.ts

providing the option to do a setup and teardown

---

CONTRIBUTING.md
website/src/pages/contributing/index.tsx

fix contributing

---

website/package.json
website/src/pages/contributing/contributors/index.tsx

Issue #181
Made quite  a lot of changes to contributors/index, added comments. Sorry if there will be any errors, as I'm not really familiar with TS, and thank you for the opportunity to work on that! It was really fun! :)

sort contributors by number of contributions

---

.github/PULL_REQUEST_TEMPLATE/full.md
.github/pull_request_template.md

- [Framework](?template=framework)
- [Tools](?template=tools)
- [Translations](?template=translations)
- [Website](?template=website)

Idrinth patch 2

---

.github/workflows/codeql.yml
.github/workflows/eslint.yml
.github/workflows/mdlint.yml
.github/workflows/spellcheck.yml
.github/workflows/stylelint.yml
.github/workflows/unittest.yml

make runs conditional,so less tools run when not absolutely required

---

website/src/index.css
website/src/pages/contributing/sponsors/index.tsx

Center sponsor image

---

examples/jsonplaceholder.typicode.com/package.json
examples/reqres.in/package.json
framework/package-lock.json
framework/package.json
package-lock.json
package.json
website/package-lock.json
website/package.json

fixes #118

---

framework/language/sp.yml

This PR solve this issue: https://github.com/Idrinth/api-bench/issues/208
- [Framework](?template=framework.md) Added spanish translation

Added spanish translation to framework

---

.github/ISSUE_TEMPLATE/bug_report.md
package.json

add md linting to github folder as well

---

framework/bin/generate-benchmark-from-open-api.js
framework/bin/make-benchmark-project.js
framework/bin/run-benchmark.js
framework/bin/run-loadtest.js
framework/language/de.yml
framework/language/en.yml
framework/package.json
framework/src/cli/bench.ts
framework/src/cli/loader.ts
framework/src/cli/make.ts
framework/src/cli/open-api-route-builder.ts
framework/src/constants.ts
framework/src/loader.ts
framework/src/main.ts
framework/test/cli/bench.ts
framework/test/cli/make.ts
framework/test/cli/open-api-route-builder.ts
website/src/pages/usage/index.tsx
website/tools/load-contributors.js

fixes #52 basics for load testing

---

framework/src/helper/function-analyzer.ts
framework/test/helper/function-analyzer.ts

adding know failures when analyzing functions

---

CONTRIBUTING.md
tools/publish.js
website/src/pages/contributing/index.tsx

adjust contributing guidelines according to feedback

---

website/.idrinth-react-file-based-routes.json
website/package-lock.json
website/package.json
website/public/locales/en/translation.json
website/src/components/loader.tsx
website/src/main.tsx
website/src/page-like/loader/offline.tsx
website/src/page-like/loader/reload.tsx
website/src/page-like/loader/wait.tsx
website/test/loader.ts

add fallback when page loading fails

---

website/language/en.yml

This pull request aims to enhance the readability and maintainability of the YAML file containing website content data. The changes focus on restructuring the file to improve clarity and consistency in formatting.
- Refactored the YAML file structure to ensure consistent indentation throughout.
- Improved the separation of sections for better organization and readability.
- Standardized the formatting of key-value pairs for uniformity across the file.
- Validated the YAML on yamllint.com
Please review and provide feedback. Thank you!

 #283 Improve readability of YAML file

---

framework/src/reporter/console-reporter.ts

format numbers in cli fixes #287

---

framework/integration/executor-job.ts
framework/integration/executor-pre-job-post.ts
framework/package-lock.json
framework/package.json
framework/src/reporter/console-reporter.ts
framework/test/executor.ts
framework/test/helper/language.ts
framework/test/main.ts
framework/test/validate-tasks.ts

Choose a template by going into `Preview` and then clicking on the link. It will reload this page and fill it with a checklist to help you make the pull request as good as possible.
- [Framework](?quick_pull=1&template=framework.md) changes to the framework
- [Tools](?quick_pull=1&template=tools.md) changes to anything in the tools directory or external tools
- [Translations](?quick_pull=1&template=translations.md) changes to the translation files
- [Website](?quick_pull=1&template=website.md) changes to the website
- [Full](?quick_pull=1&template=full.md) changes to multiple categories

Format numbers for cli

---

website/cypress/e2e/autowiring.cy.ts
website/cypress/e2e/contributing.cy.ts
website/cypress/e2e/contributors.cy.ts
website/cypress/e2e/home.cy.ts
website/cypress/e2e/imprint.cy.ts
website/cypress/e2e/license.cy.ts
website/cypress/e2e/logging.cy.ts
website/cypress/e2e/middlewares.cy.ts
website/cypress/e2e/not-found.cy.ts
website/cypress/e2e/quick-start.cy.ts
website/cypress/e2e/results.cy.ts
website/cypress/e2e/routes.cy.ts
website/cypress/e2e/sponsors.ts
website/cypress/e2e/storage.cy.ts
website/cypress/e2e/support.cy.ts
website/cypress/e2e/usage.cy.ts

Choose a template by going into `Preview` and then clicking on the link. It will reload this page and fill it with a checklist to help you make the pull request as good as possible.
- [Framework](?quick_pull=1&template=framework.md) changes to the framework
- [Tools](?quick_pull=1&template=tools.md) changes to anything in the tools directory or external tools
- [Translations](?quick_pull=1&template=translations.md) changes to the translation files
- [Website](?quick_pull=1&template=website.md) changes to the website
- [Full](?quick_pull=1&template=full.md) changes to multiple categories

fixed issue

---

website/src/index.css

Made Footer Responsive

---

website/src/pages/home/index.tsx

isse 360 faq section

---

website/src/pages/home/index.tsx

fix home layout

---

framework/language/de.yml
framework/language/en.yml
framework/src/middlewares/silent-server-validator.ts
framework/test/middlewares/silent-server-validator.ts
website/src/pages/usage/middlewares/index.tsx

fixes #356 add validator to check for info leakage

---

.github/PULL_REQUEST_TEMPLATE/documentation.md
.github/PULL_REQUEST_TEMPLATE/framework.md
.github/PULL_REQUEST_TEMPLATE/full.md
.github/PULL_REQUEST_TEMPLATE/history-ui.md
.github/PULL_REQUEST_TEMPLATE/tools.md
.github/PULL_REQUEST_TEMPLATE/translation.md
.github/pull_request_template.md

Update templates to be clearer
inspired by @pasand85 - please give some feedback to the changes

docs: add documentation pr template

---

.dictionary.txt
CONTRIBUTING.md
website/src/pages/contributing/index.tsx

add structure info to contributing

docs: add structure info to contributing

---

.github/FUNDING.yml
.github/PULL_REQUEST_TEMPLATE/full.md
.github/PULL_REQUEST_TEMPLATE/history-microservice.md
.github/pull_request_template.md
.github/workflows/codeql.yml
.github/workflows/eslint.yml
.github/workflows/mdlint.yml
.github/workflows/spellcheck.yml
.github/workflows/stylelint.yml
.github/workflows/unittest.yml
.gitignore
history-microservice/.eslintrc.cjs
history-microservice/package-lock.json
history-microservice/package.json

prepares for microservice development

churn: prepare history microservice

---

documentation-website/src/pages/usage/index.tsx
framework/bin/check-route-definitions.js
framework/integration/route-validator.ts
framework/language/en.yml
framework/package.json
framework/src/cli/check-routes.ts
framework/src/helper/job-creator.ts
framework/src/task-type.ts
framework/src/task-types.ts
framework/test/cli/bench.ts
framework/test/cli/check-routes.ts

allow the validation by binary

feature(framework): prepare validation

---

documentation-website/cypress/e2e/contributing.cy.ts
documentation-website/language/en.yml
documentation-website/package.json
documentation-website/src/pages/contributing/contributing.css
documentation-website/src/pages/contributing/index.tsx

Move texts of contributing to translation file.

feature(documentation-website): translate contributing

---

.github/PULL_REQUEST_TEMPLATE/dockerfiles.md
.github/PULL_REQUEST_TEMPLATE/full.md
.github/workflows/docker.yml
containers/gitlab-runner/Dockerfile

feat(docker): add gitlab runner

---

.dictionary.txt
.github/workflows/docker.yml
README.md
containers/gitea-action/Dockerfile
containers/gitea-action/README.md
containers/gitlab-runner/Dockerfile
framework/README.md

feature(dockerfiles): add gitea action

---

documentation-website/src/components/card.tsx
documentation-website/src/pages/contributing/index.tsx

Created card component . Card component has 3 props  titleText, titleLevel, sideMode: boolean.

Title text component

---

CONTRIBUTING.md
documentation-website/language/en.yml
documentation-website/src/pages/contributing/index.tsx

documentation: disallow force push

---

documentation-website/src/components/navbar.tsx

added slack link
Choose a template by going into `Preview` and then clicking on the link.
It will reload this page and fill it with a checklist to help you make
the pull request as good as possible.
- [Documentation-Website][DW] changes to the website

fix:Add slack link to the website #462

---

documentation-website/src/pages/contributing/contributors/index.tsx

feature(documentation-website):add contributor name as id

---

containers/api-bench-gitea-action/Dockerfile
containers/api-bench-gitlab-runner/Dockerfile
containers/api-bench-history-microservice/Dockerfile
containers/api-bench-history-website/Dockerfile
containers/api-bench/Dockerfile
tools/publish.js

add missing labels and remove static values, that lead to unnecessary rebuilds

feature(dockerfiles): remove need for recreation each version

---

documentation-website/src/components/content-unit.tsx
documentation-website/src/components/dark-light-icon.tsx
documentation-website/src/components/dark-mode-button.tsx
documentation-website/src/components/faq.tsx
documentation-website/src/components/layout.tsx
documentation-website/src/pages/license/index.tsx
framework/src/logger/console-logger.ts
framework/src/logger/wrapper.ts
framework/src/main.ts
framework/src/middlewares/access-token.ts
framework/src/middlewares/json-validator.ts
framework/src/middlewares/xml-validator.ts
framework/src/reporter/reporter.ts
framework/src/request.ts
framework/src/store.ts
framework/src/worker/runner.ts
framework/test/storage/mysql-storage.ts
history-microservice/package-lock.json
history-website/package-lock.json

code smell fixes based on sonar lint

---

.github/workflows/hadolint.yml
.hadolint.yaml

Add hadolint to lint Dockerfiles

ci: add hadolint to lint docker

---

.github/workflows/docker.yml
.github/workflows/hadolint.yml
containers/api-bench-build/Dockerfile
tools/setup.js

The build image is now prepared for building more parts of the mono-repo than just the framework.

fix(dockerimages, tools): docker build fix, setup fix

---

README.md
framework/README.md

add privacy and compliance note

feature(documentation): add privacy and compliance note

---

.gitignore
containers/api-bench-build/Dockerfile
framework/.npmignore
framework/language/en.yml
framework/package.json
framework/src/helper/language.ts
framework/src/messaging/calculator.ts
framework/tools/generate-language.js

feature(framework): move translations to ts

---

containers/api-bench-build/Dockerfile
history-microservice/package.json
history-microservice/tsconfig.json
history-website/package.json

create history services at
- /project/@idrinth/api-bench/history-microservice
- /project/@idrinth/api-bench/history-website

build history services

---

documentation-website/src/components/faq-item.tsx
documentation-website/src/components/faq.tsx
documentation-website/src/index.css

Extract FAQ element in new React component and fix up and down arrows on FAQ accordion.

refactor(documentation-website): extract FAQ element in its own component

---

tools/publish.js
tools/src/exec.js

remove dumping a password to stdout

bug(tools): remove password logging

---

documentation-website/src/components/contributor.css
documentation-website/src/components/contributor.tsx
documentation-website/src/index.css
documentation-website/src/pages/contributing/contributors/index.tsx

feature(documentation-website): extract contributor

---

documentation-website/src/components/contributor.css
documentation-website/src/components/contributor.tsx
documentation-website/src/components/hash-scroll.tsx
documentation-website/src/components/layout.tsx
documentation-website/src/constants.ts

feature(documentation-website): scroll to hash

---

documentation-website/language/en.yml
documentation-website/src/pages/home/index.tsx

bug(documentation-website): translate home

---

.dictionary.txt
README.md
mindmap/README.md

-  [x] all actions are passing
Add Readme for mindmap..

feature(documentation): add mindmap readme

---

examples/jsonplaceholder.typicode.com/.env
examples/jsonplaceholder.typicode.com/src/routes/main/create-post.js
examples/jsonplaceholder.typicode.com/src/routes/main/delete-post.js
examples/jsonplaceholder.typicode.com/src/routes/main/get-post.js
examples/jsonplaceholder.typicode.com/src/routes/main/list-posts.js
examples/jsonplaceholder.typicode.com/src/routes/main/patch-post.js
examples/jsonplaceholder.typicode.com/src/routes/main/update-post.js
examples/reqres.in/.env
examples/reqres.in/src/routes/before/login.js
examples/reqres.in/src/routes/main/create-user.js
examples/reqres.in/src/routes/main/delete-user.js
examples/reqres.in/src/routes/main/list-users.js
examples/reqres.in/src/routes/main/patch-user.js
examples/reqres.in/src/routes/main/single-user-not-found.js
examples/reqres.in/src/routes/main/single-user.js

feature(examples): use env

---

framework/language/en.yml
framework/package-lock.json
framework/src/cli/check-routes.ts

Provide validation of the Request at main..

feature(framework): Validate Request

---

documentation-website/cypress/e2e/code-of-conduct.cy.ts
documentation-website/cypress/fixtures/constants.ts
documentation-website/language/en.yml
documentation-website/src/components/footer.tsx
documentation-website/src/pages/code-of-conduct/index.tsx

Add code of Conduct to the website

feature(documentation-website): Add Code of Conduct

---

documentation-website/src/components/faq-item.css
documentation-website/src/components/faq-item.tsx
documentation-website/src/index.css
documentation-website/src/pages/faq/index.tsx

Choose a template by going into `Preview` and then clicking on the link.
It will reload this page and fill it with a checklist to help you make
the pull request as good as possible.
- [Framework][Framework] changes to the framework
- [Tools][Tools] changes to anything in the tools directory
- [Translations][Translations] changes to the translation files
- [Documentation-Website][DW] changes to the website
- [History-Website][HW] changes to the history-ui
- [History-Microservice][HM] changes to the history-microservice
- [Documentation][Documentation] changes to a md file (Readme for example)
- [Examples][Examples] adding or adjusting examples
- [DockerFiles][DF] adding or modifying dockerfiles
- [Full][Full] changes to multiple categories
[Full]: ?quick_pull=1&template=full.md …

Faq can be used with keyboard

---

.github/PULL_REQUEST_TEMPLATE/cli.md
.github/PULL_REQUEST_TEMPLATE/full.md
.github/PULL_REQUEST_TEMPLATE/mindmap.md
.github/pull_request_template.md
documentation-website/src/pages/quick-start/index.tsx
mindmap/README.md
mindmap/data.yml
mindmap/schema.json
mindmap/tools/data.js

add schema

---

mindmap/package-lock.json
mindmap/package.json
mindmap/public/.htaccess
mindmap/public/robots.txt
mindmap/src/index.css
mindmap/tools/data.js

- add cachhing
- minify content
- extract css

feature(mindmap): minification and caching

---

documentation-website/src/components/command.tsx
documentation-website/src/components/content-unit.tsx
documentation-website/test/components/content-unit.ts

refs #574
create component for documenting commands

feature(documentation-website): add command component

---

documentation-website/src/components/layout.tsx
documentation-website/src/components/loader.tsx
documentation-website/src/pages/code-of-conduct/index.tsx
documentation-website/src/pages/contributing/contributors/index.tsx
documentation-website/src/pages/contributing/index.tsx
documentation-website/src/pages/contributing/sponsors/index.tsx
documentation-website/src/pages/faq/index.tsx
documentation-website/src/pages/home/index.tsx
documentation-website/src/pages/imprint/index.tsx
documentation-website/src/pages/license/index.tsx
documentation-website/src/pages/not-found/index.tsx
documentation-website/src/pages/quick-start/index.tsx
documentation-website/src/pages/support/index.tsx
documentation-website/src/pages/usage/autowiring/index.tsx
documentation-website/src/pages/usage/index.tsx
documentation-website/src/pages/usage/logging/index.tsx
documentation-website/src/pages/usage/middlewares/index.tsx
documentation-website/src/pages/usage/results/index.tsx
documentation-website/src/pages/usage/routes/index.tsx
documentation-website/src/pages/usage/storage/index.tsx

children is now ussed instead of Outlet

refactoring(documentation-website): simplify layout

---

documentation-website/language/en.yml
documentation-website/src/components/command.tsx
documentation-website/src/constants.ts
documentation-website/src/pages/usage/index.tsx

refactor(documentation-website): use command component

---

framework/bin/run-benchmark.js
framework/bin/run-content-test.js
framework/src/cli/content.ts

Add a simple binary for content testing

feature(framework): add content testing

---

.github/workflows/year-update.yml
LICENSE
documentation-website/src/components/footer.tsx
documentation-website/src/pages/license/index.tsx
package.json
tools/update-year.js

update the license year automatically on the first of january

feature(documentation, documentation-website): auto update license year

---

CONTRIBUTING.md
documentation-website/language/en.yml
documentation-website/src/constants.ts
documentation-website/src/pages/contributing/index.tsx
mindmap/schema.json

Mindmap documentation is now in contributing

feature(documentation, documentation-website): add mindmap guidelines

---

documentation-website/language/en.yml
documentation-website/src/components/command.css
documentation-website/src/components/command.tsx
documentation-website/src/pages/usage/index.tsx

documentation of commands updated

update the docs for the new binary

---

documentation-website/src/assets/external-link-svgrepo-com.black.svg
documentation-website/src/assets/external-link-svgrepo-com.white.svg
documentation-website/src/components/command.css
documentation-website/src/components/external-link.tsx
documentation-website/src/components/header.tsx
documentation-website/src/components/social-link.tsx
documentation-website/src/index.css

- logo position fixed
- external links cleaned  up

Issue 590 fix logo position

---

documentation-website/language/en.yml
documentation-website/src/pages/usage/autowiring/index.tsx

translate autowiring

---

documentation-website/language/en.yml
documentation-website/src/pages/usage/logging/index.tsx

translate logging page

---

documentation-website/language/en.yml
documentation-website/src/pages/usage/middlewares/index.tsx

translate middleware page

---

documentation-website/language/en.yml
documentation-website/src/pages/home/index.tsx

- add missing info to the home page

add missing features to home

---

framework/integration/delay.ts
framework/integration/executor-job.ts
framework/integration/executor-pre-job-post.ts
framework/integration/iab.ts
framework/integration/main.ts

- increasetimeout for integration tests

less flaky integration tests

---

documentation-website/cypress/e2e/check-ui-mode.cy.ts

add a new Cypress test that checks the dark mode and light mode functionality

test(documentation-website): Add a cypress test for dark mode

---

.dictionary.txt
README.md

feature(documentation): update project part descriptions

---

documentation-website/src/index.css

remove unnecessary media query that were add for mobile devices. It is not needed because it is a mobile first design

fix(documentation-website): remove unnecessary media query

---

.dictionary.txt
.github/workflows/cli.spellcheck.yml
.github/workflows/documentation-website.spellcheck.yml
.github/workflows/framework.spellcheck.yml
.github/workflows/history-website.spellcheck.yml
.github/workflows/mindmap.spellcheck.yml
cli/.spellcheckerrc.yml
cli/package-lock.json
cli/package.json
documentation-website/.spellcheckerrc.yml
documentation-website/package-lock.json
documentation-website/package.json
framework/.spellcheckerrc.yml
framework/package-lock.json
framework/package.json
history-microservice/package-lock.json
history-website/.spellcheckerrc.yml
history-website/package-lock.json
history-website/package.json
mindmap/.spellcheckerrc.yml
mindmap/package-lock.json
mindmap/package.json
package-lock.json
package.json

- add spellcheck for en.yml
- add spellcheck for data.yml

feature(global): add spellcheck for data yaml files

---

.dictionary.txt
framework/language/en.yml

bug(framework): fix typos

---

.github/workflows/mindmap.eslint.yml
.github/workflows/mindmap.stylelint.yml
mindmap/.eslintrc.cjs
mindmap/.stylelintrc.json
mindmap/data.yml
mindmap/package-lock.json
mindmap/package.json
mindmap/src/index.css
mindmap/tools/data.js

feature(mindmap): enable linting

---

.github/release.yml
.github/workflows/release.yml
.npmrc
cli/.npmrc
documentation-website/.npmrc
framework/.npmrc
history-microservice/.npmrc
history-website/.npmrc
mindmap/.npmrc
tools/publish.js

- release on valid milestone closed

feature(tools): add auto-publish

---

documentation-website/src/components/list-unit.tsx
documentation-website/src/pages/contributing/contributing.css
documentation-website/src/pages/contributing/index.tsx

- reduce duplicate code on contributing

refactor(documentation-website): simplify contributing

---

.coderabbit.yaml

feature(ci): fix rabbit's tone

---

documentation-website/language/en.yml
documentation-website/src/pages/home/index.tsx

feature(documentation-website): no more bashing of competitors

---

mindmap/tools/data.js

bug(mindmap): no more await in loop

---

.github/workflows/stale.yml

feature(ci): add auto unassign/close

---

documentation-website/src/components/external-link.scss
documentation-website/src/components/external-link.tsx
documentation-website/src/components/sponsor.scss
documentation-website/src/components/t.ts
documentation-website/src/index.scss

feature(ci): extract css from index

---

examples/jsonplaceholder.typicode.com/package.json
examples/reqres.in/package.json

bug(examples): using start instead of run

---

.coderabbit.yaml
.github/workflows/cli.codeql.yml
.github/workflows/codeql.yml
.github/workflows/documentation-website.codeql.yml
.github/workflows/framework.codeql.yml
.github/workflows/history-microservice.codeql.yml
.github/workflows/history-website.codeql.yml
.github/workflows/mindmap.codeql.yml
.github/workflows/root.codeql.yml
.github/workflows/test.yml
documentation-website/cypress.config.ts
documentation-website/package-lock.json
documentation-website/package.json

feature(examples): run in parallel

---

package-lock.json
package.json
tools/print-ci.js
tools/src/constants.js

add a tool to print all locally run-able ci steps

refactor(tools): add print-ci

---

mindmap/data.yml

feature(mindmap): add linkedin survey results

---

.github/workflows/mindmap.validate.yml
mindmap/package.json
mindmap/tools/validate.js

feature(mindmap): validate data

---

tools/print-ci.js

improve the output of the tool by reducing noise

feature(ci): rework printing for easier to read output

---

framework/language/en.yml
framework/package-lock.json
framework/package.json
framework/src/cli/check-routes.ts
framework/src/reporter/console-reporter.ts
tools/setup.js

feature(framework): introduce status symbols

---

.dictionary.txt
README.md
cli/README.md
framework/README.md

fix(docs): Added social buttons in root, Framework, and cli README

---

documentation-website/language/en.yml

Issue 695 fixed

---

.dictionary.txt
documentation-website/language/en.yml
mindmap/data.yml

bug(mindmap,documentation-website): fix linkedin spelling

---

cli/README.md

docs(documentation-website):add code factor rating to CLI README

---

README.md
cli/README.md
framework/README.md

docs(documentation-website):add code factor rating to package and root readmes

---

documentation-website/src/components/breadcrumbs.tsx

Update breadcrumbs.tsx with adding <span> to fix breadcrumb nav issue

---

framework/index.ts
framework/package-lock.json
framework/package.json
framework/src/storage/postgres-storage.ts

feature(framework): introduce untested postgres storage

---

framework/src/constants.ts
framework/src/helper/default-reporter.ts
framework/src/helper/format-date.ts
framework/src/reporter/xray-cloud-reporter.ts
framework/src/reporter/xray-onpremise-reporter.ts

- cloud reporter based on env
- on premise reporter based on env

feature(framework): add xray reporters

---

.commitlintrc.json
.dictionary.txt
documentation-website/language/en.yml
documentation-website/src/pages/usage/results/index.tsx
documentation-website/src/pages/usage/storage/index.tsx

- storages listed as experimental
- reporters listed

documentation(documentation-website): add xray reporters and new storages

---

.github/workflows/cli.codeql.yml
.github/workflows/documentation-website.codeql.yml
.github/workflows/framework.codeql.yml
.github/workflows/history-microservice.codeql.yml
.github/workflows/history-website.codeql.yml
.github/workflows/mindmap.codeql.yml
.github/workflows/root.codeql.yml
documentation-website/tools/lighthouse-report.js

bug(ci): manually set values for fair comparison

---

framework/src/cli/cli.ts
framework/src/cli/config/config.ts
framework/src/cli/config/factory.ts
framework/src/cli/config/from-cli.ts
framework/src/cli/config/from-env.ts
framework/src/cli/config/to-value.ts
framework/src/constants.ts

feature(framework): the config is now build from both command line options and env

---

.github/workflows/global.prace.yml
prace.yml

feature(ci): add prace

---

cli/src/route-builder/to-filename.ts
framework/src/helper/function-analyzer.ts
tools/print-ci.js

refactor(cli,framework,tools): simplify regexp
